// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKXMl4O3FPoze8SqMTwVZPvH73cgXhr1Q',
    appId: '1:563579583896:web:62e90d851a5f527a233fed',
    messagingSenderId: '563579583896',
    projectId: 'movies-app-9fdcd',
    authDomain: 'movies-app-9fdcd.firebaseapp.com',
    storageBucket: 'movies-app-9fdcd.firebasestorage.app',
    measurementId: 'G-BSF5G8CS4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ4PDTx1ibtoWSLCVCl1q0RLuTItOdVRk',
    appId: '1:563579583896:android:8f8cda74b3a730ef233fed',
    messagingSenderId: '563579583896',
    projectId: 'movies-app-9fdcd',
    storageBucket: 'movies-app-9fdcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA60KOphFAwgM2YakVRmf4WQM7olPOmfU',
    appId: '1:563579583896:ios:52b483c1da012f10233fed',
    messagingSenderId: '563579583896',
    projectId: 'movies-app-9fdcd',
    storageBucket: 'movies-app-9fdcd.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA60KOphFAwgM2YakVRmf4WQM7olPOmfU',
    appId: '1:563579583896:ios:52b483c1da012f10233fed',
    messagingSenderId: '563579583896',
    projectId: 'movies-app-9fdcd',
    storageBucket: 'movies-app-9fdcd.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKXMl4O3FPoze8SqMTwVZPvH73cgXhr1Q',
    appId: '1:563579583896:web:86de3efef7a6cd0f233fed',
    messagingSenderId: '563579583896',
    projectId: 'movies-app-9fdcd',
    authDomain: 'movies-app-9fdcd.firebaseapp.com',
    storageBucket: 'movies-app-9fdcd.firebasestorage.app',
    measurementId: 'G-CCZC2Z4JLH',
  );
}
